# Generated by Django 3.2.20 on 2023-08-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('argentina', 'Argentina'), ('bolivia', 'Bolivia'), ('chile', 'Chile'), ('colombia', 'Colombia'), ('costa_rica', 'Costa Rica'), ('cuba', 'Cuba'), ('dominican_republic', 'Dominican Republic'), ('ecuador', 'Ecuador'), ('el_salvador', 'El Salvador'), ('equatorial_guinea', 'Equatorial Guinea'), ('guatemala', 'Guatemala'), ('honduras', 'Honduras'), ('mexico', 'Mexico'), ('nicaragua', 'Nicaragua'), ('panama', 'Panama'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('spain', 'Spain'), ('uruguay', 'Uruguay'), ('venezuela', 'Venezuela')], default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_cvimec', upload_to='images/'),
        ),
    ]
